### ISSUE TITLE
Tests Failing on Travis CI

### ISSUE THREAD

**Issue by nnutter** [genome/TestDbServer#65]
After merging #64 `master` started failing ([Travis CI #102](https://travis-ci.org/genome/TestDbServer/builds/52484401)).  I also re-ran a previously passing `master` and it started failing as well ([Travis CI #100](https://travis-ci.org/genome/TestDbServer/builds/52283304)).

Something must have changed on the Travis CI workers.

**Comment by brummett** [comment]
This looks like the same errors fixed by #70

**Comment by nnutter** [comment]
I agree, closing!
